apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: moodle
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: bitnami/mariadb:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: yes
        - name: MARIADB_USER
          value: "bn_moodle"
        - name: MARIADB_PASSWORD
          value: "bitnami"
        - name: MARIADB_DATABASE
          value: "bitnami_moodle"        
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: mariadb_data
      volumes:
      - name: mariadb_data
        persistentVolumeClaim:
          claimName: mariadb-moodle-pvc
