apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-moodle-pvc
  namespace: moodle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeName: "mariadb-moodle-pv"