apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: moodle
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.23.28
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 8443
    targetPort: 8443
    name: https
  selector:
    app: moodle