apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
  namespace: moodle
spec:
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: bitnami/moodle:latest
        env:
        - name: MOODLE_DATABASE_HOST
          value: mariadb
        - name: MOODLE_DATABASE_PORT_NUMBER
          value : "3306"
        - name: MOODLE_DATABASE_USER
          value: "root"
        - name: MOODLE_DATABASE_PASSWORD
          value: "moodle"
        - name: MOODLE_DATABASE_NAME
          value: "moodle"
        - name: MOODLE_DATABASE_PORT
          value: "3306"
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
        - mountPath: /bitnami/moodle
          name: moodle-storage
        - mountPath: /bitnami/moodledata
          name: moodledata-storage
        # links:
        #   - mariadb:database
      volumes:
      - name: moodle-storage
        hostPath:
          path: /data-nfs/moodle
          type: Directory
      - name: moodledata-storage
        hostPath:
          path: /data-nfs/moodle
          type: Directory
